spring:
  application:
    name: store
stripe:
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,RUPEE,GBP
  apiUrl: https://api.stripe.com

payment_Gateway: paypal

mail:
  host: gmail.com
  port: 233
